# Generated by Django 3.1.12 on 2025-06-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='background_perfil',
            field=models.ImageField(blank=True, default='defaults/default_background.jpg', null=True, upload_to='background_perfil'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='defaults/default_thumbnail.jpeg', null=True, upload_to='posts/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, default='Essa bio está em construção... mas você já pode me conhecer melhor interagindo comigo!', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='defaults/default_foto.png', null=True, upload_to='foto_pefil'),
        ),
    ]
