# Generated by Django 3.1.12 on 2025-05-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('crp', models.CharField(max_length=20)),
                ('area_atuacao', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
    ]
