# Generated by Django 3.1.12 on 2025-06-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app.forum'),
        ),
    ]
