# Generated by Django 3.1.12 on 2025-05-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_psicologo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Psicologo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='area_atuacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='crp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('comum', 'Comum'), ('psicologo', 'Psicólogo')], default='comum', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
